### ISSUE TITLE
Deprecation warning for env in Rails 5

### ISSUE THREAD

**Issue by lisbethmarianne** [travis-ci/travis-sso#11]
In admin v2 (currently Rails 5.0.0.1) we get this warning, for using `current_user` that comes from Travis SSO. 

`DEPRECATION WARNING: env is deprecated and will be removed from Rails 5.1 (called from current_user at /Users/Katrin/.rvm/gems/ruby-2.3.1/bundler/gems/travis-sso-f79920d5a14c/lib/travis/sso/helpers.rb:22)`

@rkh Can you please have a look if this could be a problem?

**Comment by rkh** [comment]
I think the code should just work in Rails 5.1. According to https://github.com/rails/rails/issues/23294 `request.env` will do the trick, which [the helper](https://github.com/travis-ci/travis-sso/blob/master/lib/travis/sso/helpers.rb) picks up if the `env` method isn't present.

**Comment by lisbethmarianne** [comment]
Thanks @rkh. I thought so as well. Closing this.
